import NFTList from "@/components/NFTList";
import { OwnedNft } from "alchemy-sdk";
import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home() {
  const [NFTS, setNFTs] = useState<OwnedNft[]>();
  const [address, setAddress] = useState(
    "0x9bE85844800d5985E9ddbE19773B7BFB6dAC3251"
  );

  useEffect(() => {
    fetch(`/api/get-nfts?address=${address}`)
      .then((res) => res.json())
      .then((NFTS) => {
        setNFTs(NFTS);
      });
  }, []);

  console.log(NFTS);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="m-5">{NFTS && <NFTList NFTS={NFTS} />}</main>
    </>
  );
}
